config/routes.rb
Rails.application.routes.draw do

  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  devise_for :users, controllers: { confirmations: 'users/confirmations' }

  root 'home#index'

  namespace :admin do
    resources :settings, only: [:update]
    get 'settings/edit', to: 'settings#edit'
  end

  resources :users, only: [:index, :edit, :update, :show] do
    collection do
      get 'search_mentionable'
    end
    member do
      post 'follow', to: 'users#follow'
      delete 'unfollow', to: 'users#unfollow'
      get 'follower', to: 'users#follower'
      get 'following', to: 'users#following'
    end
  end
  get 'users/mentioned_users/:name', to: 'users#mentioned_users', as: :search_mentionable

  resources :groups, except: [:destroy] do
    member do
      get 'unjoin', to: 'groups#unjoin'
      get 'join', to: 'groups#join'
      get 'members', to: 'groups#members'
    end
    collection do
      get 'owned', to: 'groups#owned'
      get 'extraneous', to: 'groups#extraneous'
    end
  end

  scope shallow_path: 'comment' do
    resources :posts, only: [:create, :destroy, :show] do
      post 'like', to: 'posts#like'
      delete 'unlike/:id', to: 'posts#unlike', as: :unlike
      resources :comments, only: [:create, :destroy] do
        post 'like', to: 'comments#like'
        delete 'unlike/:id', to: 'comments#unlike', as: :unlike
      end
    end
  end
  resources :attachments, only: [:destroy, :create]

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
  has_many :posts, dependent: :destroy
  belongs_to :creator, class_name: User

  validates :name, uniqueness: true, format: { with: /\A([a-z]|\s)+\z/i, message: 'only letters' }, length: { maximum: 255 }
  validates :name, :description, presence: true

  after_create :add_creator_to_member

  def self.sort_by_creator(collection, direction)
    collection.joins(:creator).order("users.name #{ direction }")
  end

  def self.sort(collection, column, direction)
    collection.order(column => direction)
  end

  def owner?(current_user)
    creator == current_user
  end

  def self.fetch_groups(term)
    Group.where('name ilike ? ', '%' + term + '%').map { |u| [u, false] }
  end

  private

    def add_creator_to_member
      members.push creator
    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :fetch_group, only: [:join, :unjoin, :update, :edit, :show, :members]
  before_action :fetch_user_groups
  before_action :allow_modify, only: [:edit, :update]
  before_action :allow_unjoin, only: :unjoin
  before_action :allow_join, only: :join
  before_action :sorting_valid?, only: [:join, :extraneous, :owned]

  def index
    @groups = current_user.groups.includes(:creator)
    @groups = sort(@groups)
  end

  def extraneous
    @groups = current_user.search_extraneous.includes(:creator)
    @groups = sort(@groups)
  end

  def owned
    @groups = current_user.owned_groups.includes(:creator)
    @groups = sort(@groups)
  end

  def new
    @group = Group.new
  end

  def create
    group = current_user.owned_groups.create(permitted_params)
    if group.save
      flash[:notice] = t('.success', scope: :flash)
      redirect_to :groups
    else
      flash[:error] = t('.failure', scope: :flash)
      redirect_to :new_group
    end
  end

  def unjoin
    if @group.members.destroy(current_user)
      flash[:notice] = t('.success', scope: :flash)
    else
      flash[:error] = t('.failure', scope: :flash)
    end
    redirect_to :groups
  end

  def join
    if @group.members.push(current_user)
      flash[:notice] = t('.success', scope: :flash)
    else
      flash[:error] = t('.failure', scope: :flash)
    end
    redirect_to :groups
  end

  def edit
  end

  def update
    if @group.update(permitted_params)
      flash[:notice] = t('.success', scope: :flash)
      redirect_to :groups
    else
      flash[:error] = t('.failure', scope: :flash)
      render :edit
    end
  end

  def show
    #FIX: What is group is not found. Handle it in before_action -DONE
    initialize_post
    initialize_comment
    #FIX: Refactor #includes -DONE
    @posts = @group.posts.order(created_at: :desc).includes(:user, :post_documents, :comments)
  end

  def members
    #FIX: We should not have post form on group members page. Please confirm with PM DONE
    initialize_post
    @members = @group.members.page params[:page]
  end

  private

    def allow_modify
      unless current_user.admin? || @group.creator == current_user
        flash[:error] = t('access.failure', scope: :flash)
       redirect_to :groups
      end
    end

    def permitted_params
      params.require(:group).permit(:name, :description)
    end

    def fetch_group
      @group = Group.where(id: params[:id]).first
      unless @group
        flash[:error] = t('record.failure', scope: :flash)
        redirect_to :groups
      end
    end

    def allow_unjoin
      if @group.creator == current_user || @group.members.exclude?(current_user)
        flash[:error] = t('.failure', scope: :flash)
        redirect_to :groups
      end
    end

    def allow_join
      if @group.members.include? current_user
        flash[:error] = t('.failure', scope: :flash)
        redirect_to :groups
      end
    end

    def sorting_valid?
      (['desc', 'asc'].include? params[:direction] and ['name', 'creator'].include?(params[:order]))
    end

    def sort(collection)
      order = sort_order
      column = sort_column
      if params[:column] == 'creator'
        Group.sort_by_creator(collection, order).page params[:page]
      else
        Group.sort(collection, column, order.to_sym).page params[:page]
      end
    end

end

app/views/groups/_create_post.html.erb
<%= nested_form_for @post, class: 'form-horizontal' do |f| %>

    <%= render 'shared/posts_form_fields', locals: {f: f} %>
    <%= f.hidden_field :group_id, value: @group.id %>

<% end %>

app/views/groups/_form.html.erb
  <article class='create-group col-md-12'>
    <fieldset class='form-group'>
      <%= f.label :name, class: 'control-label' %>
        <font color='red'> *  </font>
      <%= f.text_field :name, class: 'form-control' %>
    </fieldset>
    <fieldset class='form-group'>
      <%= f.label :description, class: 'control-label' %>
        <font color='red'> * </font>
      <%= f.text_area :description, class: 'form-control' %>
    </fieldset>
    <fieldset class='form-group'>
      <%= f.submit class: 'btn btn-success' %>
    </fieldset>
  </article>

app/views/groups/_group_list.html.erb
<div class='group-block mt-10'>
  <ul class='nav group-sub'>
    <li class=<%= 'active' if controller_name == 'groups' && action_name == 'index' %>><%= link_to 'My groups', :groups %> </li>
    <li class=<%= 'active' if controller_name == 'groups' && action_name == 'extraneous' %>> <%= link_to 'Other groups', :extraneous_groups %> </li>
    <li class=<%= 'active' if controller_name == 'groups' && action_name == 'owned' %>> <%= link_to 'Owned groups', :owned_groups %> </li>
  </ul>
  <div>
    <table class="table table-striped table-hover ">
      <tr>
        <th class='group-width'>Name
          <%= link_to_order :name %>
        </th>
        <th>Description</th>
          <% if action != :owned %>
            <th>Creator
                <%= link_to_order :creator %>
            </th>
          <% end %>
        <th>Action</th>
      </tr>
      <% @groups.each do |group| %>
        <tr>
          <td class='group-width'> <%= group.name %> </td>
          <td> <%= group.description.truncate(25) %> </td>

          <% if action != :owned %>
            <td> <%= group.creator.name %> </td>
          <% end %>
          <td>
            <%= link_to '', group_path(group), title:'view', class:'view fa fa-search' %>
            <%= group_join_link(group) %>
            <% if admin_logged_in? || group.owner?(current_user) %>
              <%= link_to :'', edit_group_path(group), title:'edit', class:'edit fa fa-edit' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
    <%= paginate @groups %>
  </div>
</div>

app/views/groups/_show_group_details.html.erb
<h2> <%= @group.name.capitalize %> </h2>
  <%= link_to 'Members', members_group_path(@group), class:'pull-right' %>
<div class="user-data pb-15">
	<%= @group.description %>
</div>
<div class='join-link'>
  <% if @group.creator != current_user %>
    <%= group_join_link(@group) %>
  <% end %>
</div>
<% if @group.members.include? current_user %>
  <%= render 'groups/create_post' %>
<% end %>

app/views/groups/edit.html.erb
<section class="edit-details pull-left mob-bot-margin">
	<article class="col-md-6 col-md-offset-4 edit-det-inr mt-15 pb-15 chng-pwd">
	  	<h2 class="mb-10">Update</h2>
		<%= form_for @group, html: { class: 'form-horizontal'} do |f| %>
	  	<%= render 'form', {f: f} %>
		<% end %>
	</article>
</section>

app/views/groups/extraneous.html.erb
<%= render 'group_list', action: :extraneous %>

app/views/groups/index.html.erb
<%= render 'group_list', action: :index %>

app/views/groups/members.html.erb
<section class='group-detail p-20 mt-10 mob-bot-margin'>
  <%= render 'show_group_details' %>
</section>
<article class="group-block mt-20">
  <table class="table table-striped table-hover ">
    <tr>
      <th>Name </th>
      <th>Description</th>
      <th>Action</th>
    </tr>
    <% @members.each do |member| %>
      <tr>
        <td> <%= member.name %> </td>
        <td> <%= member.email %> </td>
        <td>
          <%= link_to '', user_path(member), class:'view fa fa-search' %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= paginate @members %>
</article>

app/views/groups/new.html.erb
<section class="edit-details pull-left mob-bot-margin">
	<article class="col-md-6 col-md-offset-4 edit-det-inr mt-15 pb-15 chng-pwd">
		<%= form_for @group, html: { class: 'form-horizontal'} do |f| %>
	  	<h2 class='col-md-offset-2'>Create</h2>
	  	<%= render 'form', {f: f} %>
		<% end %>
	</article>
</section>

app/views/groups/owned.html.erb
<%= render 'group_list', action: :owned %>

app/views/groups/show.html.erb
<div class='group-detail p-20 mt-10 mob-bot-margin'>
  <%= render 'groups/show_group_details' %>
  <%= render 'shared/posts' %>
</div>