config/routes.rb
Rails.application.routes.draw do

  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  devise_for :users, controllers: { confirmations: 'users/confirmations' }

  root 'home#index'

  namespace :admin do
    resources :settings, only: [:update]
    get 'settings/edit', to: 'settings#edit'
  end

  resources :users, only: [:index, :edit, :update, :show] do
    collection do
      get 'search_mentionable'
    end
    member do
      post 'follow', to: 'users#follow'
      delete 'unfollow', to: 'users#unfollow'
      get 'follower', to: 'users#follower'
      get 'following', to: 'users#following'
    end
  end
  get 'users/mentioned_users/:name', to: 'users#mentioned_users', as: :search_mentionable

  resources :groups, except: [:destroy] do
    member do
      get 'unjoin', to: 'groups#unjoin'
      get 'join', to: 'groups#join'
      get 'members', to: 'groups#members'
    end
    collection do
      get 'owned', to: 'groups#owned'
      get 'extraneous', to: 'groups#extraneous'
    end
  end

  scope shallow_path: 'comment' do
    resources :posts, only: [:create, :destroy, :show] do
      post 'like', to: 'posts#like'
      delete 'unlike/:id', to: 'posts#unlike', as: :unlike
      resources :comments, only: [:create, :destroy] do
        post 'like', to: 'comments#like'
        delete 'unlike/:id', to: 'comments#unlike', as: :unlike
      end
    end
  end
  resources :attachments, only: [:destroy, :create]

end

app/models/user.rb
#FIXME_AB: Indexes missing on almost all tables DONE
class User < ActiveRecord::Base

  START_YEAR = 1970
  USER_DETAILS = %i(name about_me job_title email date_of_birth mobile joining_date)

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable

  has_one :image, as: :attachment, dependent: :destroy
  has_many :likes
  #FIXME_AB: instead of groups_members, i think we should name it as group_memberships DONE
  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships
  has_many :owned_groups, class_name: Group, foreign_key: :creator_id
  #FIXME_AB: Are you sure we want to destroy all related records when we destroy user?. AFAIR we agreed to delete user if there is no record associated with him, else disable him. Please consult with your PM DONE
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :follows, class_name: Follow, foreign_key: :follower_id
  has_many :followings, class_name: Follow, foreign_key: :followed_user_id
  has_many :followers, through: :follows, source: :followed_user
  has_many :followed_users, through: :followings, source: :follower

  accepts_nested_attributes_for :image

  validates :name, presence: :true, format: { with: /\A([a-z]|\s)+\z/i, message: 'only letters' }, length: { maximum: 255 }

  validates_uniqueness_of :name, :case_sensitive => false

  validate :email_matches_company_domain

  scope :enabled, -> { where(enabled: true) }

  def active_for_authentication?
    super && enabled
  end

  def search_extraneous
    Group.where.not(id: self.group_ids)
  end

  def self.sort(collection, column, direction)
    collection.order(column => direction)
  end

  def large_thumbnail_url
    image.attachment.url(:large)
  end

  def following?(user)
    followed_users.include? user
  end

  def number_of_followers
    followers.count
  end

  def self.fetch_users(term)
    User.where('name ilike ? ', '%' + term + '%').map { |u| [u, u.image ? u.image.attachment.url(:logo) : false] }
  end

  private

    def email_matches_company_domain
      if COMPANY['domain'] != email.split('@').last
        errors.add(:email, "domain does not match with #{COMPANY['domain']}")
      end
    end

end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  protected

    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource)
      root_path
    end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    self.resource.name = resource_params[:name]
    self.resource.enabled = true
    self.resource.save
    yield resource if block_given?
    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
      set_flash_message(:notice, flash_message) if is_flashing_format?
      sign_in(resource_name, resource)
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      respond_with resource
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #FIX: Use only instead of except DONE
  before_action :fetch_user, only: [:follower, :following, :edit, :show, :update, :follow, :unfollow]

  before_action :allow_modify, only: [:update, :edit]

  before_action :fetch_mentioned_user, only: :mentioned_users

  ALLOWED_PARAMS = %i(name date_of_birth mobile about_me job_title
                      admin joining_date enabled) +
                      [ image_attributes: %i(attachment id) ]

  def index
    respond_to do |format|
      format.html do
        #FIX: Move to a method #fetch_users. Inside that call #filter_users for filtering by letter DONE
        fetch_users
      end
      format.json do
        #FIX: Make a method in User, Group for searching. DONE
        #FIX: Move json creation to a private method. DONE
        #FIX: Try to use serializer for creating this json.
        #FIX: Group has no image. so no need to check DONE
        render json: fetch_user_groups
      end
    end

  end

  def follower
    @users = @user.followers
    #FIX: Use symbol syntax for rendering DONE
    render :index
  end

  def following
    @users = @user.followed_users
    #FIX: Use symbol syntax for rendering DONE
    render :index
  end

  #FIX: See if we can change the search_mentionable user link href to /users/:id. Then we can completely remove this action.
  def mentioned_users
    initialize_posts_comments
    render :show
  end

  #FIX: Rename to #search_mentionable DONE
  def search_mentionable
    respond_to do |format|
      format.json do
        #FIX: Search users with names beginning with term only DONE
        data = { users: User.where('name ilike ? ',params[:term] + '%').map { |user| { name: user.name, image: user.image.attachment.url(:logo) } } }
        render json: data
      end
    end
  end

  def edit
    @user.build_image unless @user.image
  end

  def show
    initialize_posts_comments
  end

  def update
    if @user.update(permitted_params)
      flash[:notice] = t('.success', scope: :flash)
      redirect_to :users
    else
      flash[:error] = t('.failure', scope: :flash)
      render :edit
    end
  end

  def follow
    if @user.followers << current_user
      #FIX: Use single method for follow/unfollow success just like in post controller #like DONE
      data = { followed: true, unfollow_path: unfollow_user_path(@user) }
    else
      data = { followed: false }
    end
    respond_to do |format|
      format.json do
        render json: data
      end
    end
  end

  def unfollow
    if @user.followers.delete current_user
      #FIX: Use single method for follow/unfollow failure just like in post controller #unlike
      data = { followed: true, follow_path: follow_user_path(@user) }
    else
      data = { followed: false }
    end
    respond_to do |format|
      format.json do
        render json: data
      end
    end
  end

  private

    def initialize_posts_comments
      initialize_comment
      initialize_post
      @posts = @user.posts.order(created_at: :desc)
    end

    def permitted_params
      params.require(:user).permit *ALLOWED_PARAMS
    end

    def fetch_user
      @user = User.where(id: params[:id]).first
      unless @user
        flash[:error] = t('record.failure', scope: :flash)
        redirect_to :users
      end
    end

    def fetch_mentioned_user
      @user = User.where('name ilike ? ',params[:name].split('@').last ).first
      unless @user
        flash[:error] = t('record.failure', scope: :flash)
        redirect_to :users
      end
    end

    def filtered_users
      if /[a-z]/i.match params[:letter]
        #FIX: See if we can write this as #where('name ilike ?%', params[:letter][0]) DONE
        #FIX: We don't need to take first letter from params[:letter]. Assume we will receive a single letter in params. DONE
        @users.where('name ilike ?', params[:letter] + '%').order(name: :asc)
      else
        @users
      end
    end

    def allow_modify
      unless current_user.admin? || @user == current_user
        flash[:error] = t('access.failure', scope: :flash)
        redirect_to :users
      end
    end

    def fetch_users
      @user = current_user
      @users = current_user.admin? ? User.all : User.enabled
      @users = filtered_users
    end

    def fetch_user_groups
     { users: User.fetch_users(params[:term]),
       groups: Group.fetch_groups(params[:term]) }
    end

end

app/views/users/_follow_unfollow.html.erb
<div class='follow-user'>
  <% if !creator_logged_in?(user) %>
    <% if current_user.following?(user) %>
      <%= link_to 'Unfollow', unfollow_user_path(user),{class: 'btn btn-danger unfollow', 'data-method' => 'Delete', 'data-remote' => true }%>
    <% else %>
      <%= link_to 'Follow', follow_user_path(user),{class: 'btn btn-success follow', 'data-method' => 'Post', 'data-remote' => true }%>
    <% end %>
  <% end %>
</div>

app/views/users/_show_user_card.html.erb
<div class='container-bottom clr-bth ovr-hdn pt-10 pb-10'>
  <div class='no-padding lib-item' data-category='view'>
    <div class='lib-panel'>
      <div class='user-detail'>
        <div class='col-md-2 col-sm-2 col-xs-6'>
          <% #FIXME_AB: I would prefer to move user.image.attachment.url(:large) to user model as a method: large_thumbnail_url DONE -%>
          <%= user.image ? image_tag(user.image.attachment.url, class: 'lib-img') : missing_image_tag %>
          <% #FIXME_AB: above if user don't have image, no image should not come as text, should be a missing image thumbnail DONE -%>
          <!-- #FIX: missing image tag can be returned from helper and used at all places DONE -->
        </div>
        <div class='col-md-10 col-sm-10 col-x6-6'>
          <div class='lib-row lib-header'>
            <div class="username-n-email pull-left">
              <%= link_to user.name.capitalize, user_path(user) %>
              <small class='pull-left pt-5'><%= user.email %></small>
            </div>
            <%= render 'follow_unfollow', user: user %>
            <% if can_edit_user?(user) %>
            <div class='pull-right edit-user'>
              <%= link_to '', edit_user_path(user), title:'edit', class:"edit fa fa-edit" %>
            </div>
            <% end %>
          </div>
          <div class='lib-row lib-desc pull-right clr-bth pt-5'>
            <% #FIXME_AB: What is the format of date you are displaying? 2014-11-10 08:52:24 UTC DONE -%>
            <%= user.joining_date.to_s(:long) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<section class="edit-details pull-left mob-bot-margin">
  <% if creator_logged_in?(@user) %>
    <%= render 'users/registrations/side_bar' %>
  <% end %>
  <article class='col-md-7 col-md-offset-5 edit-det-inr mt-15 pb-15'>
    <%= form_for @user, html: { class: 'form-horizontal col-md-12'} do |f| %>
      <h2 class='mb-0'>edit user details</h2>
      <fieldset class='form-group col-md-offset-4'>
        <%= render partial: 'shared/error_message', locals: {errors: @user.errors} %>
      </fieldset>
      <fieldset class='form-group'>
        <%= f.label :name, class: 'control-label' %>
          <font color='red'>
          *
        </font>
        <%= f.text_field :name, class: 'form-control' %>
      </fieldset>
      <fieldset class='form-group'>
        <%= f.label :about_me, class: 'control-label' %>
        <%= f.text_area :about_me, class: 'form-control' %>
      </fieldset>
      <fieldset class='form-group'>
        <%= f.fields_for :image do |attach| %>
          <%= f.label :attachment, class: 'control-label' %>
          <div class="fields">
            <%= attach.file_field :attachment %>
            <span class="attachment-btn absolute">Browse</span>
          </div>
        <% end %>
      </fieldset>
      <fieldset class='form-group'>
        <%= f.label :job_title, class: 'control-label' %>
        <%= f.text_field :job_title, class: 'form-control' %>
      </fieldset>
      <fieldset>
        <%= f.label :date_of_birth, class: 'control-label margin-left' %>
      </fieldset>
      <fieldset class='form-group'>
        <%= date_select :user, :date_of_birth, start_year: User::START_YEAR, end_year: Time.current.year, class: 'form-control' %>
      </fieldset>
      <fieldset class='form-group'>
        <%= f.label :mobile, class: 'control-label' %>
        <%= f.text_field :mobile, class: 'form-control' %>
      </fieldset>
      <% #FIXME_AB: ??? -%>
      <% if admin_logged_in? && !creator_logged_in?(@user) %>
        <fieldset class='form-group'>
          <%= f.label :admin, class: 'control-label' %>
          <%= f.check_box :admin %>
        </fieldset>
        <fieldset class='form-group'>
          <%= f.label :enabled, class: 'control-label' %>
          <%= f.check_box :enabled %>
        </fieldset>
        <fieldset class='form-group'>
          <%= f.label :joining_date, class: 'control-label' %>
          <%= date_select :user, :joining_date, start_year: User::START_YEAR, end_year: Time.current.year, class: 'form-control' %>
        </fieldset>
      <% end %>
      <fieldset class='form-group'>
        <%= f.submit 'Update user', class: 'btn btn-success' %>
      </fieldset>
    <% end %>
  </article>
</section>

app/views/users/index.html.erb
<div class="group-people mt-10">
  <ul class='nav group-sub'>
    <% if controller_name == 'users' && action_name == 'index' %>
      <li class='active'> <%= link_to 'All users', users_path %> </li>
    <% else %>
      <li class='list-groups-items'> <%= link_to 'All users', users_path %> </li>
    <% end %>
    <% if controller_name == 'users' && action_name == 'follower' %>
      <li class='active'> <%= link_to 'Followers', follower_user_path(@user) %> </li>
    <% else %>
      <li class='list-groups-items'> <%= link_to 'Followers', follower_user_path(@user) %> </li>
    <% end %>
    <% if controller_name == 'users' && action_name == 'following' %>
      <li class='active'> <%= link_to 'Following', following_user_path(@user) %> </li>
    <% else %>
      <li class='list-groups-items'> <%= link_to 'Following', following_user_path(@user) %> </li>
    <% end %>
  </ul>
  <ul class='list-inline pb-10'>
    <% ApplicationHelper::ALPHABETS.each do |alphabet| %>
        <% if params[:letter] == alphabet %>
          <li class='active'>
            <%= link_to alphabet, users_path(letter: alphabet) %>
          </li>|
        <% else %>
          <li class='list-groups-items'>
            <%= link_to alphabet, users_path(letter: alphabet) %>
          </li>|
        <% end %>
    <% end %>
  </ul>
  <div class='user-block'>
  <% #FIXME_AB: What if there were no users DONE -%>
    <% if @users %>
      <% @users.each do |user| %>
        <%= render 'show_user_card', user: user %>
      <% end %>
    <% else %>
      No Users
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class='container dashbard-body'>
  <div class='col-md-6 col-md-offset-1 group-block'>
    <table class='table table-striped table-hover table-bordered center-align mt-20'>
      <h2 class="user-hed"> User details
        <%= render 'follow_unfollow', user: @user %>
      </h2>
        <tr>
          <td> Name </td>
          <td> <%= @user.name %> </td>
        </tr>
        <tr>
          <td> About me </td>
          <td> <%= @user.about_me %> </td>
        </tr>
        <tr>
          <td> Job title </td>
          <td> <%= @user.job_title %> </td>
        </tr>
        <tr>
          <td> Email </td>
          <td> <%= @user.email %> </td>
        </tr>
        <tr>
          <td> Date Of Birth </td>
          <td>
            <% if @user.date_of_birth %>
              <%= @user.date_of_birth.to_s(:long) %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td> Mobile </td>
          <td> <%= @user.mobile %> </td>
        </tr>
        <tr>
          <td> Joining date </td>
          <td> <%= @user.joining_date.to_s(:long) %> </td>
        </tr>

      <tr>
        <td> Attachment </td>

        <td> <%= @user.image ? image_tag(@user.image.attachment.url) : missing_image_tag %>
        </td>
      </tr>

      <tr>
        <td> number of followers </td>
        <td> <%= link_to @user.number_of_followers, follower_user_path(@user), class: 'follower-numbers' %> </td>
      </tr>

    </table>
  </div>
  <div class='user-posts pull-left'>
    <%= render 'shared/posts' %>
  </div>
</div>