config/routes.rb
Rails.application.routes.draw do

  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  devise_for :users, controllers: { confirmations: 'users/confirmations' }

  root 'home#index'

  namespace :admin do
    resources :settings, only: [:update]
    get 'settings/edit', to: 'settings#edit'
  end

  resources :users, only: [:index, :edit, :update, :show] do
    collection do
      get 'search_mentionable'
    end
    member do
      post 'follow', to: 'users#follow'
      delete 'unfollow', to: 'users#unfollow'
      get 'follower', to: 'users#follower'
      get 'following', to: 'users#following'
    end
  end
  get 'users/mentioned_users/:name', to: 'users#mentioned_users', as: :search_mentionable

  resources :groups, except: [:destroy] do
    member do
      get 'unjoin', to: 'groups#unjoin'
      get 'join', to: 'groups#join'
      get 'members', to: 'groups#members'
    end
    collection do
      get 'owned', to: 'groups#owned'
      get 'extraneous', to: 'groups#extraneous'
    end
  end

  scope shallow_path: 'comment' do
    resources :posts, only: [:create, :destroy, :show] do
      post 'like', to: 'posts#like'
      delete 'unlike/:id', to: 'posts#unlike', as: :unlike
      resources :comments, only: [:create, :destroy] do
        post 'like', to: 'comments#like'
        delete 'unlike/:id', to: 'comments#unlike', as: :unlike
      end
    end
  end
  resources :attachments, only: [:destroy, :create]

end

app/views/shared/_create_comments.html.erb
<!-- #FIX: Rename to _post_comment_form.html.erb -->
<div class='col-lg-10'>
  <%= nested_form_for [post, @comment], html: { class: 'form-horizontal col-lg-12' ,remote: true, class: 'create-comment'} do |f| %>

    <div class='control-group'>
      <%= f.text_area :content, class: 'form-control inputbox' %>
    </div>

      <%= f.hidden_field :post_id, value: post.id %>

    <br>
    <div class='comment-post'>
      <div class='control-group'>
        <%= f.fields_for :comment_documents do |doc| %>
          <%= doc.file_field :attachment %>
        <% end %>
      </div>
      <%= f.link_to_add 'Add attachment', :comment_documents %>
    </div>

    <div class='control-group col-lg-offset-10'>
      <%= f.submit 'Post', class: 'btn btn-primary' %>
    </div>

  <% end %>
  <br> <br>
</div>

app/views/shared/_error_message.html.erb
<ul class='nav'>
	<% errors.full_messages.each do |message| %>
		<li> <%= message %> </li>
	<% end %>
</ul>

app/views/shared/_group.html.erb
<fieldset class='user-container'>
	<figure class='profile-image-container'>
    <a href='#'>
      <%= current_user.image ? image_tag(current_user.image.attachment.url) : missing_image_tag %>
    </a>
	</figure>
  <label class="pt-5 pb-5 m-0">
    <a href='#'>
      <%= current_user.name.capitalize %>
    </a>
  </label>
  <ul class='followers'>
    <li>
    <%= link_to current_user.number_of_followers, follower_user_path(current_user) %> followers
    </li>
    <li>
    <%= link_to current_user.followings.count, following_user_path(current_user), class: 'follower-numbers' %> followings
    </li>
    <li>
      <%= link_to 'New group', :new_group %>
    </li>
    <li class='list-group sidebar-width'>
    <%= link_to 'My groups', groups_path, class: 'list-group-item mainactive' %>
    <% current_user.groups.each do |group| %>
      <% if controller_name == 'groups' && action_name = 'show' && params['id'] == group.id.to_s %>
        <%= link_to group.name, group, class: 'list-group-item active' %>
      <% else %>
        <%= link_to group.name, group, class: 'list-groups-items list-group-item' %>
      <% end %>
    <% end %>
  </ul>
</fieldset>

app/views/shared/_post_comment_form.html.erb
<!-- #FIX: Rename to _post_comment_form.html.erb DONE -->
<div>
  <%= nested_form_for [post, @comment], html: { class: 'form-horizontal col-lg-12' ,remote: true, class: 'create-comment'} do |f| %>
    <div class='control-group mb-10'>
      <%= f.text_area :content, class: 'form-control inputbox' %>
    </div>
    <%= f.hidden_field :post_id, value: post.id %>
    <div class='comment-post'>
      <div class='control-group'>
        <%= f.fields_for :comment_documents do |doc| %>
        <%= doc.file_field :attachment %>
        <span class='attachment-btn absolute'>Browse</span>
      <% end %>
      </div>
      <%= f.link_to_add 'Add attachment', :comment_documents %>
    </div>
    <div class='attachment-type'>
      Only image, pdf, excel and doc files are supported.
    </div>
    <div class='control-group col-lg-offset-10'>
      <%= f.submit 'Comment', class: 'btn btn-success add-comment' %>
    </div>
  <% end %>
</div>

app/views/shared/_posts.html.erb
<!-- #FIX: Rename file to _posts.html.erb DONE -->
<section>
  <% @posts.each do |post| %>
  <%= render 'shared/show_post', post: post %>
  <% end %>
</section>

app/views/shared/_posts_form_fields.html.erb
<fieldset>
  <%= locals[:f].text_area :content, placeholder: 'What\'s on your mind?', class: 'form-control inputbox' %>
</fieldset>
<article class='post-submit pt-15 ovr-hdn'>
  <fieldset class='col-md-3 col-sm-3 col-xs-3 pull-left pull-left pl-0'>
    <%= locals[:f].fields_for :post_documents do |attach| %>
      <%= attach.file_field :attachment %>
      <span class='attachment-btn absolute'>Browse</span>
    <% end %>
    <%= locals[:f].link_to_add 'Add attachment', :post_documents %>
  </fieldset>
  <fieldset class='post-submit-button col-md-5 col-sm-5 col-xs-5 pull-right pr-0'>
    <%= locals[:f].submit %>
    <span class='attachment-type'>
      Only image, pdf, excel and doc files are supported.
    </span>
  </fieldset>
</article>

app/views/shared/_show_attachment.html.erb
<!-- Button trigger modal -->

<%= image_tag image.attachment.url, {size: '35x35', 'data-toggle' => 'modal', 'data-target' => '#' + image.id.to_s} %>

<!-- Modal -->
<div class="modal fade" id=<%= image.id %> tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body post-image">
        <button class="close" data-dismiss="modal">X</button>
        <%= image_tag(image.attachment.url, size: '300x300') %>
      </div>
      <div class="modal-footer">
        <a href="<%= image.attachment.url %>" download="<%= image.attachment.name %>"> Download </a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_show_post.html.erb
<article class='post-division mt-15 fill clr-both ovr-hdn p-20'>
    <% if post.user.image %>
      <%= image_tag(post.user.image.attachment.url(:thumb)) %>
    <% end %>
    <span class='name-bold'>
      <%= post.user.name.capitalize %>
    </span>
    <div class='post-margin'>
      <%= linkify_mentions(linkify_hashtags(post.content)) %>
        <% post.post_documents.each do |document| %>
        <div class='attachment comment-margin'>
          <span>
            <% if document.attachment_content_type.split('/').first == 'image' %>
            <%= render 'shared/show_attachment', image: document %>
            <% else %>
            <%= link_to attachment_type(document), document.attachment.url %>
            <%= document.attachment_file_name %>
            <% end %>
          </span>
          <% if can_edit_user?(post.user) %>
          <%= link_to image_tag('delete.png'), attachment_path(document), method: :delete, remote: true, class: 'delete-attachment' %>
          <% end %>
        </div>
      <% end %>
      <div class='like-n-dlt mt-10'>
        <span class='count'>
          <%= post.likes.count %>
        </span>
        <%= link_to_like_unlike post, :post %>
        <% if can_edit_user?(post.user) %>
        <span class='display-dlt'>
          <%= link_to image_tag('delete.png'), post_path(post.id), method: :delete, class: 'delete-post' %>
        </span>
        <% end %>
      </div>
    </div>
    <%= render 'home/show_comments', post: post %>
    <% if( !post.group || current_user.groups.include?(post.group) || current_user.admin? ) %>
    <%= render 'shared/post_comment_form', post: post %>
    <% end %>
</article>