config/routes.rb
Rails.application.routes.draw do

  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  devise_for :users, controllers: { confirmations: 'users/confirmations' }

  root 'home#index'

  namespace :admin do
    resources :settings, only: [:update]
    get 'settings/edit', to: 'settings#edit'
  end

  resources :users, only: [:index, :edit, :update, :show] do
    collection do
      get 'search_mentionable'
    end
    member do
      post 'follow', to: 'users#follow'
      delete 'unfollow', to: 'users#unfollow'
      get 'follower', to: 'users#follower'
      get 'following', to: 'users#following'
    end
  end
  get 'users/mentioned_users/:name', to: 'users#mentioned_users', as: :search_mentionable

  resources :groups, except: [:destroy] do
    member do
      get 'unjoin', to: 'groups#unjoin'
      get 'join', to: 'groups#join'
      get 'members', to: 'groups#members'
    end
    collection do
      get 'owned', to: 'groups#owned'
      get 'extraneous', to: 'groups#extraneous'
    end
  end

  scope shallow_path: 'comment' do
    resources :posts, only: [:create, :destroy, :show] do
      post 'like', to: 'posts#like'
      delete 'unlike/:id', to: 'posts#unlike', as: :unlike
      resources :comments, only: [:create, :destroy] do
        post 'like', to: 'comments#like'
        delete 'unlike/:id', to: 'comments#unlike', as: :unlike
      end
    end
  end
  resources :attachments, only: [:destroy, :create]

end

app/views/layouts/_search_bar.html.erb
<!-- <div class='navbar-center blue-color'> -->
<ul class='nav'>
  <div class='pull-left logo-position'>
    <%= link_to(image_tag(@logo.image.attachment.url(:thumb)), :root) %>
  </div>
  <li class='dropdown more-position pull-right'>
    <a href='#' class='dropdown-toggle more-link-color' data-toggle='dropdown'><%= current_user.name.capitalize %>
      <b class='caret'></b>
    </a>
    <ul class='dropdown-menu'>
      <li>
       <%= link_to 'Edit Profile', edit_user_path(current_user) %>
      </li>
      <% if admin_logged_in? %>
      <li>
        <%= link_to 'Settings', admin_settings_edit_path %>
      </li>
      <% end %>
      <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      </li>
    </ul>
  </li>
  <div class='search-user col-md-2 col-sm-4 pull-right mt-10'>
    <input type ="hidden" id="user_user_id">
  </div>
</ul>
<!-- </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vammer</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <header class='header'>
      <div class='container'>
        <div class='row'>
          <% if user_signed_in? %>
            <div class='search-header'>
              <%= render 'layouts/search_bar' %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <section class='bodycontainer ovr-hdn mt-20 pb-20'>
      <!-- #FIX: Fade out flash messages after some time -->
      <% if flash[:notice] %>
        <div class="control-group alert alert-success ml-15 mr-15">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:error] %>
        <div class="control-group alert alert-danger ml-15 mr-15">
          <%= flash[:error] %>
        </div>
      <% end %>
      <% if current_user %>
        <aside class='col-md-2 col-sm-3'>
          <%= render 'shared/group' %>
        </aside>
        <article class='navigation-bar-new col-md-6 col-sm-9'>
          <ul class="nav nav-tabs">
            <li role="presentation" class=<%= 'active' if request.fullpath == '/' %> > <small class='fa fa-home'></small><%= link_to 'Home', root_path %> </li>
            <li role="presentation" class=<%= 'active' if request.fullpath == '/groups' %> ><small class='fa fa-group'></small> <%= link_to 'Group', groups_path %> </li>
            <li role="presentation" class=<%= 'active' if request.fullpath == '/users' %>><small class='fa fa-user'></small> <%= link_to 'People', users_path %> </li>
          </ul>
      <% end %>
      <%= yield %>
    </section>
    <div id='spinner'>
      <img src="/assets/spinner.gif" id='show-spinner'>
    </div>
  </body>
</html>